### PR TITLE
Financial Assessment.

### PR DESCRIPTION
**Pull request by awong-dev**
Implments
  doc/orig-1010ez/1010ez-apply-12.PNG
  doc/orig-1010ez/1010ez-apply-15.PNG

### CODE REVIEW

**Comment by awong-dev** [comment]
moar htmlz.

**Comment by alex** [comment]
Was this intended for the other alex?

**Comment by awong-dev** [comment]
@alex mis-click. It was meant for emily.

**Comment by alex** [comment]
:+1:

**Pull request merged**
